/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_FuenteInformacion;

/**
 *
 * @author altna
 */
public class FRM_FuenteInformacion extends javax.swing.JFrame {

  
    public Controlador_FRM_FuenteInformacion controlador_FRM_FuenteInformacion;
    
    public FRM_FuenteInformacion() 
    {
        initComponents();
        controlador_FRM_FuenteInformacion=new Controlador_FRM_FuenteInformacion(this);
       gUI_BotonesInformacionFuente1.agregarEventos(controlador_FRM_FuenteInformacion);
    }
    

    
    public boolean archivosPlanosSeleccionado()
    {
        return this.jrb_ArchivosPlanos.isSelected();
    }
    
    public boolean basesDeDatosSeleccionado()
    {
        return this.jrb_BasesDeDatos.isSelected();
    }
    
    public boolean xMLSeleccionado()
    {
        return this.jrb_XML.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Bienvenido = new javax.swing.JLabel();
        jl_Instruccion = new javax.swing.JLabel();
        jrb_ArchivosPlanos = new javax.swing.JRadioButton();
        jrb_BasesDeDatos = new javax.swing.JRadioButton();
        jrb_XML = new javax.swing.JRadioButton();
        gUI_BotonesInformacionFuente1 = new Vista.GUI_BotonesInformacionFuente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Bienvenido.setText("¡Bienvenido!");

        jl_Instruccion.setText("Por favor elija la fuente de informacion que va a utilizar");

        jrb_ArchivosPlanos.setText("Archivos Planos");

        jrb_BasesDeDatos.setText("Bases de Datos");

        jrb_XML.setText("XML");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_ArchivosPlanos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_BasesDeDatos)
                            .addComponent(jl_Bienvenido)
                            .addComponent(jl_Instruccion))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_XML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gUI_BotonesInformacionFuente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Bienvenido)
                .addGap(18, 18, 18)
                .addComponent(jl_Instruccion)
                .addGap(18, 18, 18)
                .addComponent(jrb_ArchivosPlanos)
                .addGap(18, 18, 18)
                .addComponent(jrb_BasesDeDatos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_XML)
                    .addComponent(gUI_BotonesInformacionFuente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesInformacionFuente gUI_BotonesInformacionFuente1;
    private javax.swing.JLabel jl_Bienvenido;
    private javax.swing.JLabel jl_Instruccion;
    private javax.swing.JRadioButton jrb_ArchivosPlanos;
    private javax.swing.JRadioButton jrb_BasesDeDatos;
    private javax.swing.JRadioButton jrb_XML;
    // End of variables declaration//GEN-END:variables
}
