/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_FuenteInformacion;

/**
 *
 * @author altna
 */
public class FRM_FuenteInformacion extends javax.swing.JFrame {

    /**
     * Creates new form FRM_FuenteInformacion
     */
    public Controlador_FRM_FuenteInformacion controlador;
    public FRM_FuenteInformacion() {
        initComponents();
        controlador = new Controlador_FRM_FuenteInformacion(this);
    }
    
    public boolean archivosPlanosSeleccionado()
    {
     return this.jrb_ArchivosPlanos.isSelected();
    }
    
    public boolean baseDatosSeleccionado()
    {
        return this.jrb_BasesDatos.isSelected();
    }
    
    public boolean xMLSeleccionado()
    {
        return this.jrb_XML.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrb_ArchivosPlanos = new javax.swing.JRadioButton();
        jrb_BasesDatos = new javax.swing.JRadioButton();
        jrb_XML = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¡Bienvenido!");

        jLabel2.setText("Por favor, elija la fuente de informacion con la que desea trabajar");

        jrb_ArchivosPlanos.setText("Archivos Planos");
        jrb_ArchivosPlanos.setActionCommand("archivosPlanos");

        jrb_BasesDatos.setText("Bases de Datos");
        jrb_BasesDatos.setActionCommand("basesDatos");

        jrb_XML.setText("XML");
        jrb_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_XMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_XML)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jrb_ArchivosPlanos)
                    .addComponent(jrb_BasesDatos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jrb_ArchivosPlanos)
                .addGap(18, 18, 18)
                .addComponent(jrb_BasesDatos)
                .addGap(18, 18, 18)
                .addComponent(jrb_XML)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_XMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_XMLActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jrb_ArchivosPlanos;
    private javax.swing.JRadioButton jrb_BasesDatos;
    private javax.swing.JRadioButton jrb_XML;
    // End of variables declaration//GEN-END:variables
}
