/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoUsuarios;
import java.beans.Statement;
import java.sql.ResultSet;

/**
 *
 * @author altna
 */
public class GUI_InformacionUsuario extends javax.swing.JPanel {
    
    Controlador_FRM_MantenimientoUsuarios Usuario;
   
    public GUI_InformacionUsuario() {
        initComponents();
    }
    
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[3];
        arreglo[0]=this.jt_NombreCompleto.getText();
        arreglo[1]=this.jt_NombreUsuario.getText();
        arreglo[2]=this.jp_Contraseña.getText();
        
        return arreglo;
    }
    
    public void resetearInterfaz()
    {
        this.jt_NombreCompleto.setText("");
        this.jt_NombreUsuario.setText("");
        this.jp_Contraseña.setText("");
    }
    
    public void mostrarInformacion(String arreglo [])
    {
        this.jt_NombreCompleto.setText(arreglo[0]);
        this.jt_NombreUsuario.setText(arreglo[1]);
    }
    
    public String devolverNombreUsuario()
    {
        return this.jt_NombreUsuario.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_NombreUsuario = new javax.swing.JTextField();
        jp_Contraseña = new javax.swing.JPasswordField();
        jc_Tipo = new javax.swing.JComboBox();

        jLabel1.setText("Nombre Completo");

        jLabel2.setText("Nombre Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Tipo");

        jt_NombreCompleto.setText("                                  ");

        jt_NombreUsuario.setText("                    ");

        jp_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_ContraseñaActionPerformed(evt);
            }
        });

        jc_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Administrador" }));
        jc_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_TipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_NombreUsuario)
                        .addComponent(jp_Contraseña)
                        .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addComponent(jc_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jp_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jc_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jp_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_ContraseñaActionPerformed

    private void jc_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_TipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jc_Tipo;
    private javax.swing.JPasswordField jp_Contraseña;
    private javax.swing.JTextField jt_NombreCompleto;
    private javax.swing.JTextField jt_NombreUsuario;
    // End of variables declaration//GEN-END:variables
}
